name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: mkskaushalya
          template: classic
          base: activity, community, repositories, metadata
          config_octicon: yes
          config_timezone: Asia/Colombo
          config_twemoji: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year